sudo: required
language: node_js
node_js:
  - '10'
before_install:
  - sudo apt-get install libcairo2-dev libjpeg62-turbo-dev libpango1.0-dev libgif-dev build-essential g++
install: npm i
jobs:
  include:
    - stage: test
      script: bash ./Travis/test.sh
dist: bionic