sudo: true
language: node_js
node_js:
  - '10'
before_install:
  - sudo apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev 
install: npm i
jobs:
  include:
    - stage: test
      script: bash ./Travis/test.sh
dist: trusty