version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.1
    working_directory: ~/repo

    steps:
      - checkout
      - run:
        - name: 'Install deps for Canvas'
        - install: 'sudo apt install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev'

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: npm run lint


